(() => {
 const data={
  central:{title:'Central Park',copy:'A lush, open-air neighborhood in the heart of the ship. Stroll through gardens, enjoy al fresco dining, live music, and handcrafted cocktails.',image:'central-park.jpg',venues:[['150 Central Park','Specialty dining','Upscale steakhouse'],["Jamie’s Italian",'Specialty dining','Rustic Italian favorites'],['Trellis Bar','Bar','Cocktails beneath the trees'],['Chops Grille','Specialty dining','Classic steakhouse']]},
  pool:{title:'Pool Deck',copy:'Sunshine, swimming, whirlpools, waterslides, and open-air fun high above the ocean.',image:'pool-deck.jpg',venues:[['Main Pool','Included','Poolside relaxation'],['Solarium','Included','Adults-only retreat'],['Perfect Storm','Included','Waterslides'],['Pool Bars','Bar','Drinks by the water']]},
  entertainment:{title:'Entertainment Place',copy:'The ship’s energetic show district for live performances, comedy, ice shows, and unforgettable nights.',image:'entertainment.jpg',venues:[['Royal Theater','Entertainment','Live productions'],['Studio B','Entertainment','Ice shows'],['Comedy Live','Entertainment','Comedy club']]},
  boardwalk:{title:'Boardwalk',copy:'A playful open-air neighborhood with family attractions, casual dining, and the AquaTheater.',image:'boardwalk.jpg',venues:[['AquaTheater','Entertainment','High-diving shows'],['Carousel','Included','Classic family ride'],['Boardwalk Dog House','Included dining','Casual bites'],['Johnny Rockets','Specialty dining','Burgers and shakes']]},
  promenade:{title:'Royal Promenade',copy:'A lively indoor boulevard for cafés, shopping, music, parades, and people-watching.',image:'promenade.jpg',venues:[['Café Promenade','Included dining','Coffee and snacks'],["Sorrento’s",'Included dining','Pizza'],['Schooner Bar','Bar','Piano music'],['Shopping','Explore','Shops and boutiques']]},
  youth:{title:'Youth Zone',copy:'Dedicated spaces for kids and teens to play, create, and make new friends.',image:'youth-zone.jpg',venues:[['Adventure Ocean','Included','Kids programming'],['Teen Spaces','Included','Teen hangouts'],['Arcade','Activity','Games'],['Family Activities','Included','All-ages fun']]},
  spa:{title:'Vitality Spa',copy:'A peaceful retreat for treatments, fitness, wellness classes, and quiet time.',image:'vitality-spa.jpg',venues:[['Vitality Spa','Specialty','Treatments and massages'],['Fitness Center','Included','Ocean-view workouts'],['Salon','Specialty','Hair and beauty'],['Wellness Classes','Activity','Mind and body']]}
 };
 const title=document.querySelector('#n-title'),copy=document.querySelector('#n-copy'),image=document.querySelector('#n-image'),heading=document.querySelector('#venue-heading'),cards=document.querySelector('#venue-cards');
 function show(key){const x=data[key]; title.textContent=x.title; copy.textContent=x.copy; image.src=`assets/neighborhoods/${x.image}`; image.alt=`${x.title} on Harmony of the Seas`; heading.textContent=`Venues in ${x.title}`; cards.innerHTML=x.venues.map(v=>`<article><span>${v[1]}</span><h3>${v[0]}</h3><p>${v[2]}</p></article>`).join(''); document.querySelectorAll('.neighborhood').forEach(b=>b.classList.toggle('active',b.dataset.neighborhood===key));}
 document.querySelectorAll('.neighborhood').forEach(b=>b.addEventListener('click',()=>show(b.dataset.neighborhood))); show('central');
 const stage=document.querySelector('#ship-interactive'),img=stage.querySelector('img'); let scale=1,rx=0,ry=0,down=false,x0=0,y0=0;
 const draw=()=>img.style.transform=`scale(${scale}) rotateX(${ry}deg) rotateY(${rx}deg)`;
 stage.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(1,Math.min(2.2,scale+(e.deltaY<0?.12:-.12)));draw()},{passive:false});
 stage.addEventListener('pointerdown',e=>{down=true;x0=e.clientX;y0=e.clientY;stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!down)return;rx=Math.max(-16,Math.min(16,rx+(e.clientX-x0)*.08));ry=Math.max(-9,Math.min(9,ry-(e.clientY-y0)*.05));x0=e.clientX;y0=e.clientY;draw()});['pointerup','pointercancel','pointerleave'].forEach(evt=>stage.addEventListener(evt,()=>down=false));
})();
