(() => {
 const data={
  central:{title:'Central Park',copy:'Step into a living garden at sea — over ten thousand real plants, trees, and vines thriving eight decks above the ocean. Wander winding pathways to candlelit dinners, sip handcrafted cocktails beneath the canopy, and catch live musicians as the stars come out. It is the most magical (and most surprising) place on the entire ship.',image:'central-park.jpg',venues:[['150 Central Park','Specialty dining','Upscale steakhouse'],["Jamie’s Italian",'Specialty dining','Rustic Italian favorites'],['Trellis Bar','Bar','Cocktails beneath the trees'],['Chops Grille','Specialty dining','Classic steakhouse']]},
  pool:{title:'Pool Deck',copy:'This is where the party lives! Splash between pools and bubbling whirlpools, race down the Perfect Storm waterslides, claim a lounger in the sun, and let the pool band and frozen drinks carry you straight into vacation mode — all with endless ocean views in every direction.',image:'pool-deck.jpg',venues:[['Main Pool','Included','Poolside relaxation'],['Solarium','Included','Adults-only retreat'],['Perfect Storm','Included','Waterslides'],['Pool Bars','Bar','Drinks by the water']]},
  entertainment:{title:'Entertainment Place',copy:'Broadway-caliber productions, professional ice-skating spectaculars, live comedy, and full theatrical stage shows — every single night. The hardest part of your evening will be choosing which jaw-dropping performance to see first. Arrive early; these shows fill up for a reason!',image:'entertainment.jpg',venues:[['Royal Theater','Entertainment','Live productions'],['Studio B','Entertainment','Ice shows'],['Comedy Live','Entertainment','Comedy club']]},
  boardwalk:{title:'Boardwalk',copy:'Pure boardwalk nostalgia with a wow factor: ride a hand-carved carousel, grab hot dogs and milkshakes, then watch Olympic-level divers plunge ten stories into the AquaTheater pool as the sun sets behind them. Fun by day, absolutely unforgettable by night.',image:'boardwalk.jpg',venues:[['AquaTheater','Entertainment','High-diving shows'],['Carousel','Included','Classic family ride'],['Boardwalk Dog House','Included dining','Casual bites'],['Johnny Rockets','Specialty dining','Burgers and shakes']]},
  promenade:{title:'Royal Promenade',copy:'The buzzing main street of the ship — a glittering indoor boulevard lined with cafés, duty-free shopping, and bars where the music never seems to stop. Time it right and a full-blown parade will march past your table. Grab a coffee, find a bench, and watch the whole ship stroll by.',image:'promenade.jpg',venues:[['Café Promenade','Included dining','Coffee and snacks'],["Sorrento’s",'Included dining','Pizza'],['Schooner Bar','Bar','Piano music'],['Shopping','Explore','Shops and boutiques']]},
  youth:{title:'Youth Zone',copy:'Kids may never want to leave: award-winning Adventure Ocean programming, teen-only lounges, an arcade packed with games, and new friends from all over the world. Parents get a night out; kids get the best week of their year. Everybody wins.',image:'youth-zone.jpg',venues:[['Adventure Ocean','Included','Kids programming'],['Teen Spaces','Included','Teen hangouts'],['Arcade','Activity','Games'],['Family Activities','Included','All-ages fun']]},
  spa:{title:'Vitality Spa',copy:'Your serene escape above the sea — melt into a massage, unwind in the thermal suite, take a sunrise yoga class, or hit the ocean-view fitness center. Come aboard for the celebration, leave feeling like a brand-new person.',image:'vitality-spa.jpg',venues:[['Vitality Spa','Specialty','Treatments and massages'],['Fitness Center','Included','Ocean-view workouts'],['Salon','Specialty','Hair and beauty'],['Wellness Classes','Activity','Mind and body']]}
 };
 const title=document.querySelector('#n-title'),copy=document.querySelector('#n-copy'),image=document.querySelector('#n-image'),heading=document.querySelector('#venue-heading'),cards=document.querySelector('#venue-cards');
 function show(key){const x=data[key]; title.textContent=x.title; copy.textContent=x.copy; image.src=`assets/neighborhoods/${x.image}`; image.alt=`${x.title} on Harmony of the Seas`; heading.textContent=`Venues in ${x.title}`; cards.innerHTML=x.venues.map(v=>`<article><span>${v[1]}</span><h3>${v[0]}</h3><p>${v[2]}</p></article>`).join(''); document.querySelectorAll('.neighborhood').forEach(b=>b.classList.toggle('active',b.dataset.neighborhood===key));}
 document.querySelectorAll('.neighborhood').forEach(b=>b.addEventListener('click',()=>show(b.dataset.neighborhood))); show('central');
 const stage=document.querySelector('#ship-interactive'),img=stage.querySelector('img'); let scale=1,rx=0,ry=0,down=false,x0=0,y0=0;
 const draw=()=>img.style.transform=`scale(${scale}) rotateX(${ry}deg) rotateY(${rx}deg)`;
 stage.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(1,Math.min(2.2,scale+(e.deltaY<0?.12:-.12)));draw()},{passive:false});
 stage.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse')return;down=true;x0=e.clientX;y0=e.clientY;stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!down)return;rx=Math.max(-16,Math.min(16,rx+(e.clientX-x0)*.08));ry=Math.max(-9,Math.min(9,ry-(e.clientY-y0)*.05));x0=e.clientX;y0=e.clientY;draw()});['pointerup','pointercancel','pointerleave'].forEach(evt=>stage.addEventListener(evt,()=>down=false));
})();
